apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nfs-haha
  namespace: default
spec:
  appId: myapp
  componentId: mycomp
  chart:
    oss:
      cloudProvider: aliyun
      regionId: oss-cn-hangzhou
      ackSecret: xxx
      ackId: xxx
      bucket: lstack-helm-chart
      key: dev/charts/nfs-server-v1.0.tgz
      ackEncrypted: true
      useCache: true
  values:
    replicaCount: 2